# Issue Labels
- color: d73a4a
  name: bug
  description: Something isn't working
- color: cfd3d7
  name: duplicate
  description: This issue or pull request already exists
- color: a2eeef
  name: enhancement
  description: New feature or request
- color: 7057ff
  name: good first issue
  description: Good for newcomers
- color: 008672
  name: help wanted
  description: Extra attention is needed
- color: e4e669
  name: invalid
  description: This doesn't seem right
- color: d876e3
  name: question
  description: Further information is requested
- color: ffffff
  name: wontfix
  description: This will not be worked on

# Type labels
- color: 1D76DB
  name: 'type: breaking'
  description: Represents a breaking change to the API surface
- color: 1D76DB
  name: 'type: feature'
  description: Represents a new feature that's been added
- color: 1D76DB
  name: 'type: bug'
  description: Represents a bug that has been fixed
- color: 1D76DB
  name: 'type: maintenance'
  description: Represents a chore that has been completed, such as updating a dockerfile
- color: 1D76DB
  name: 'type: docs'
  description: Represents a change to the documentation
- color: 1D76DB
  name: 'type: dependencies'
  description: Represents an automated change to the dependencies
- color: 1D76DB
  name: 'type: security'
  description: Represents a security issue