name: 'GoLang - Build'
description: 'Builds multiple versions of a Go service complete with test coverage'
inputs:
  architectures:
    description: 'A CSV list of the architectures to build the docker image for'
    required: false
    default: 'darwin/amd64,darwin/arm64,linux/amd64,linux/arm64,windows/amd64,windows/arm64'
  checkForLatestVersion:
    description: 'Check to see whether the version of Go to use is the latest version and download if appropriate'
    required: false
    default: 'true'
  outputDirectory:
    description: 'The directory of the binaries that are built'
    required: false
    default: ''
  version:
    description: 'The version of Go to use'
    required: false
    default: '1.18.1'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.version }}
        check-latest: ${{ inputs.checkForLatestVersion }}

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Verify dependencies
      run: |
        for i in $(echo ${{ inputs.architectures }} | tr "," "\n")
        do
          GOOS=${i%/*} GOARCH=${i#*/} go mod tidy
          GOOS=${i%/*} GOARCH=${i#*/} go mod verify
        done

    - name: Build
      if: ${{ inputs.outputDirectory == '' }}
      run: |
        for i in $(echo ${{ inputs.architectures }} | tr "," "\n")
        do
          GOOS=${i%/*} GOARCH=${i#*/} go build -v ./...
          GOOS=${i%/*} GOARCH=${i#*/} go build -v ./...
        done

    - name: Build
      if: ${{ inputs.outputDirectory != '' }}
      run: |
        for i in $(echo ${{ inputs.architectures }} | tr "," "\n")
        do
          GOOS=${i%/*} GOARCH=${i#*/} go build -o ${{ inputs.outputDirectory }} -v ./...
          GOOS=${i%/*} GOARCH=${i#*/} go build -o ${{ inputs.outputDirectory }} -v ./...
        done

    - name: Run go vet
      run:  |
        for i in $(echo ${{ inputs.architectures }} | tr "," "\n")
        do
          GOOS=${i%/*} GOARCH=${i#*/} go vet
        done

    - name: Run StaticCheck
      uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: latest
        install-go: false

    - name: Run tests
      run:  |
        for i in $(echo ${{ inputs.architectures }} | tr "," "\n")
        do
          GOOS=${i%/*} GOARCH=${i#*/} go test -race -vet=off ./...
        done