name: 'Docker - Multi-Arch Build'
description: 'Build docker image which supports multi-architecture, if desired'
inputs:
  architectures:
    description: 'A CSV list of the architectures to build the docker image for'
    required: false
    default: 'linux/amd64,linux/arm64/v8'
  buildArgs:
    description: 'A list of build arguments to pass to the build context'
    required: false
    default: ''
  context:
    description: 'The context directory to pass to the build. Default: .'
    required: false
    default: '.'
  cosignPublicKey:
    description: 'The public key used to verify the signed container'
    required: false
    default: ''
  cosignPrivateKeyPassword:
    description: 'The password to unlock the signing private key'
    required: false
    default: ''
  dockerfile:
    description: 'The Dockerfile that you wish to build. Default: ./Dockerfile'
    required: false
    default: './Dockerfile'
  imageName:
    description: 'The name of the image that you want to push. Default: user/repo'
    required: false
    default: ${{ github.repository }}
  pushImagesOnComplete:
    description: 'Whether or not to push the docker images after the build completes. Default: false'
    required: false
    default: 'false'
  token:
    description: 'The Github token that is used to publish the container images'
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: ${{ inputs.architectures }}

    - uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ hashFiles(inputs.dockerfile, inputs.context) }}
        restore-keys: |
          buildx-

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.imageName }}
        flavour: |
          latest=false
        tags: |
          type=sha
          type=semver,pattern={{version}}

    - name: Github Packages Login
      uses: docker/login-action@v2
      if: ${{ inputs.pushImagesOnComplete == 'true' }}
      with: 
        registry: 'ghcr.io'
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build
      uses: docker/build-push-action@v3
      with:
        build-args: ${{ inputs.buildArgs }}
        builder: ${{ steps.buildx.outputs.name }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        outputs: type=image
        platforms: ${{ inputs.architectures }}
        push: ${{ inputs.pushImagesOnComplete }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Check Supplychain
      if: ${{ inputs.PushImagesOnComplete == 'true' }}
      shell: bash
      env:
        COSIGN_PASSWORD: ${{ inputs.cosignPrivateKeyPassword }}
        TAGS: ${{ steps.meta.outputs.tags }}
      run: |
        echo "Creating container attestation..."
        echo "${TAGS}" | xargs -I{} syft attest --key cosign.key -o spdx-json --recursive {} > ${{ inputs.context }}/container.att.json

        echo "Checking for vulnerabilities..."
        echo "${TAGS}" | xargs -I{} grype {} --add-cpes-if-none --fail-on critical --scope AllLayers

    - name: Sign with cosign
      if: ${{ inputs.PushImagesOnComplete == 'true' }}
      shell: bash
      env:
        COSIGN_PUBLIC_KEY: ${{ inputs.cosignPublicKey }}
        COSIGN_PASSWORD: ${{ inputs.cosignPrivateKeyPassword }}
        TAGS: ${{ steps.meta.outputs.tags }}
      run: |
        echo "${TAGS}" | xargs cosign sign -r --key cosign.key
        echo "${TAGS}" | xargs cosign verify --key env://COSIGN_PUBLIC_KEY
