name: Publish Release Assets
description: 'Sets up the necessary tools for supply chain security such as cosign, syft and grype'
inputs:
  outputDirectory:
    description: 'The directory of which files to upload'
    required: false
    default: ./out
runs:
  using: 'composite'
  steps:
    - name: Upload release files
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      shell: bash
      working-directory: ${{ inputs.outputDirectory }}
      run: |
        echo ${{ github.token }} | gh auth login --with-token
        for filename in ./* ; do
          [ -e "$filename" ] || continue
          echo "Processing $filename ..."
          gh release upload ${{ github.event.release.tag_name }} $filename
        done
