name: Update common files

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/file-copy.yml'
      - 'common/**'

jobs:
  copy-file:
    strategy:
      fail-fast: false
      matrix:
        repository: [
          '.engineering',
          '.github'
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'src'
          ref: 'main'
          persist-credentials: false

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'dest'
          ref: 'main'
          repository: 'projectkeas/${{ matrix.repository }}'
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
          persist-credentials: false

      - name: Copy common files to new repo
        shell: bash
        run: cp -rvT src/common/ dest/

      - name: Check For New Files
        id: newFiles
        shell: bash
        working-directory: dest
        run: |
          git add -A
          git status --porcelain | wc -l
          if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
            echo "::set-output name=hasNewFiles::true"
          else
            echo "::set-output name=hasNewFiles::false"
          fi

      - name: Push New Files
        if: ${{ steps.newFiles.outputs.hasNewFiles == 'true' }}
        shell: bash
        working-directory: dest
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git commit -m "maint: Updated common files from ref: projectkeas/.engineering@$GITHUB_SHA"
          git push "https://keas-bot:${{secrets.BOT_TOKEN}}@github.com/projectkeas/${{matrix.repository}}.git" --set-upstream "main"

