name: Sync Labels
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/label-sync.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ secrets.ALL_REPO_PAT }} | gh auth login --with-token
          gh repo list --source --json nameWithOwner -t '{{range .}}{{tablerow .nameWithOwner}}{{end}}' projectkeas
        shell: bash
        id: listRepos
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_REPO_PAT }}
        with:
          manifest: .github/labels.yml
          repository: |
            projectkeas/.engineering
            projectkeas/.github
            projectkeas/.template-service
            projectkeas/service-test
