name: Main

on:
  workflow_call:
    inputs:
      fetchDepth:
        required: false
        type: number
        default: 1
      tags:
        required: true
        type: string
      pushImagesOnComplete:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ inputs.fetchDepth }}
          submodules: 'true'
      - name: Build & Verify
        uses: projectkeas/.engineering/.github/actions/go-build@main
        with:
          outputDirectory: ./out
      - name: Build Docker Image
        uses: projectkeas/.engineering/.github/actions/docker-build@main
        with:
          context: ./out
          pushImagesOnComplete: ${{ inputs.pushImagesOnComplete }}
          tags: ${{ inputs.tags }}
